import { ArrowDown, ArrowUp, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { useState } from "react";
import { createCategory, deleteCategory, updateCategory } from "../api/documents";
import { useAdminCategories } from "../hooks/useAdminCategories";
import type { CategoryDefinition } from "../types/document";

export function AdminCategoriesPage() {
  const { categories, loading, error, reload, setCategories } = useAdminCategories(); const [message, setMessage] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const ordered = (items: CategoryDefinition[]) => [...items].sort((a, b) => a.position - b.position);
  const add = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const element = event.currentTarget; const form = new FormData(element); try { const { category } = await createCategory({ name: form.get("name"), shortName: form.get("shortName"), description: form.get("description"), position: categories.length ? Math.max(...categories.map(item => item.position)) + 10 : 10 }); setCategories(current => ordered([...current, category])); element.reset(); setMessage("Category created."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Category could not be created."); } finally { setBusy(false); } };
  const save = async (event: React.FormEvent<HTMLFormElement>, item: CategoryDefinition) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { const { category } = await updateCategory(item.id, { name: form.get("name"), shortName: form.get("shortName"), description: form.get("description"), position: Number(form.get("position")) }); setCategories(current => ordered(current.map(entry => entry.id === category.id ? category : entry))); setEditing(null); setMessage("Category updated."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Category could not be updated."); } finally { setBusy(false); } };
  const move = async (item: CategoryDefinition, direction: -1 | 1) => { const index = categories.findIndex(category => category.id === item.id); const neighbor = categories[index + direction]; if (!neighbor) return; setBusy(true); try { const [{ category: moved }, { category: adjacent }] = await Promise.all([updateCategory(item.id, { position: neighbor.position }), updateCategory(neighbor.id, { position: item.position })]); setCategories(current => ordered(current.map(entry => entry.id === moved.id ? moved : entry.id === adjacent.id ? adjacent : entry))); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Category order could not be updated."); } finally { setBusy(false); } };
  return <main className="admin-content"><div className="admin-page-heading"><p className="eyebrow">Organization</p><h1>Categories</h1><p>Create and maintain the categories used by the document library.</p></div>{message && <div className="admin-notice" role="status">{message}</div>}
    <form className="admin-form category-form" onSubmit={add}><label>Name<input name="name" required maxLength={100}/></label><label>Short label<input name="shortName" required maxLength={40}/></label><label>Description<input name="description" maxLength={240}/></label><button className="primary-button" disabled={busy}><Plus size={18}/>Add Category</button></form>
    {loading ? <div className="admin-resource-state" role="status"><span className="loading-ring"/>Loading categories…</div> : error ? <div className="admin-resource-state" role="alert"><h2>Categories unavailable</h2><p>{error}</p><button className="primary-button" onClick={() => void reload()}><RefreshCw size={17}/>Retry</button></div> : <div className="category-admin-list" aria-label="Document categories">{categories.map((item, index) => editing === item.id ? <form className="category-edit-row" key={item.id} onSubmit={event => save(event, item)}><label>Name<input name="name" defaultValue={item.name} required maxLength={100}/></label><label>Short label<input name="shortName" defaultValue={item.shortName} required maxLength={40}/></label><label>Description<input name="description" defaultValue={item.description} maxLength={240}/></label><label>Order<input name="position" type="number" min="0" defaultValue={item.position}/></label><div className="row-actions"><button type="submit" disabled={busy}>Save</button><button type="button" onClick={() => setEditing(null)}><X/>Cancel</button></div></form> : <article key={item.id}><div className="category-order"><button disabled={index === 0 || busy} onClick={() => void move(item, -1)} aria-label={`Move ${item.name} up`}><ArrowUp/></button><button disabled={index === categories.length - 1 || busy} onClick={() => void move(item, 1)} aria-label={`Move ${item.name} down`}><ArrowDown/></button></div><div><strong>{item.name}</strong><span>{item.shortName}</span><p>{item.description || "No description"}</p></div><div className="row-actions"><button disabled={busy} onClick={() => setEditing(item.id)}><Pencil/>Edit</button><button disabled={busy} className="danger" onClick={async () => { if (!confirm(`Delete “${item.name}”?`)) return; setBusy(true); try { await deleteCategory(item.id); setCategories(current => current.filter(entry => entry.id !== item.id)); setMessage("Category deleted."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Category could not be deleted."); } finally { setBusy(false); } }}><Trash2/>Delete</button></div></article>)}{categories.length === 0 && <div className="admin-empty">No categories have been created.</div>}</div>}
  </main>;
}
