import { ArrowDown, Building, Mail, Phone, RefreshCw, Search, SearchX } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getLibrary } from "../api/documents";
import { CategoryOverview } from "../components/CategoryOverview";
import { DocumentRow } from "../components/DocumentRow";
import { siteConfig } from "../config/site";
import type { LibraryResponse } from "../types/document";

export function HomePage() {
  const [library, setLibrary] = useState<LibraryResponse>({ categories: [], documents: [] });
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [status, setStatus] = useState<"loading"|"ready"|"error">("loading");
  const load = () => { setStatus("loading"); getLibrary().then(data => { setLibrary(data); setStatus("ready"); }).catch(() => setStatus("error")); };
  // Initial API synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(load, []);
  const results = useMemo(() => { const q = query.trim().toLowerCase(); return library.documents.filter(item => (filter === "all" || item.categoryId === filter) && (!q || [item.title, item.category?.name, item.category?.shortName, String(item.year)].some(value => value?.toLowerCase().includes(q)))); }, [filter, query, library.documents]);
  const chooseCategory = (id: string) => { setFilter(id); const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches; document.getElementById("document-results")?.scrollIntoView({ behavior: reducedMotion ? "auto" : "smooth", block: "start" }); };
  return <main id="top">
    <section className="hero" aria-labelledby="hero-title"><div className="hero-pattern" aria-hidden="true" /><div className="shell hero-inner"><p className="eyebrow">Official association records</p><h1 id="hero-title">{siteConfig.subtitle}</h1><p className="hero-description">{siteConfig.description} Clear, current, and available in one trusted place.</p><a className="hero-link" href="#documents">Browse documents <ArrowDown size={17} /></a></div></section>
    <section className="documents-section shell" id="documents" aria-labelledby="documents-heading"><div className="section-heading"><div><p className="eyebrow">Document library</p><h2 id="documents-heading">Find association records</h2></div><p>{library.documents.length} documents available</p></div>
      {status === "loading" ? <div className="library-state" role="status"><span className="loading-ring" />Loading document library…</div> : status === "error" ? <div className="library-state" role="alert"><SearchX aria-hidden="true" /><h3>Document library unavailable</h3><p>Please try again in a moment.</p><button className="primary-button" onClick={load}><RefreshCw size={17} aria-hidden="true"/>Retry</button></div> : <><label className="search-field"><Search aria-hidden="true" size={21} /><span className="sr-only">Search documents</span><input type="search" placeholder="Search documents..." value={query} onChange={event => setQuery(event.target.value)} /></label><CategoryOverview categories={library.categories} documents={library.documents} onSelect={chooseCategory} /><div className="filter-bar" aria-label="Filter by category"><button type="button" aria-pressed={filter === "all"} className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>All Documents</button>{library.categories.map(category => <button type="button" aria-pressed={filter === category.id} className={filter === category.id ? "active" : ""} onClick={() => setFilter(category.id)} key={category.id}>{category.shortName}</button>)}</div><div id="document-results" className="document-results" aria-live="polite"><div className="results-summary"><strong>{results.length} {results.length === 1 ? "document" : "documents"}</strong>{filter !== "all" && <span>in {library.categories.find(category => category.id === filter)?.name}</span>}</div>{results.length ? results.map(item => <DocumentRow document={item} key={item.id} />) : <div className="empty-state"><SearchX size={28} aria-hidden="true" /><h3>No documents found</h3><p>{library.documents.length ? "Try a different title, category, or year." : "No published documents are available yet."}</p>{library.documents.length > 0 && <button type="button" onClick={() => { setQuery(""); setFilter("all"); }}>Clear search and filters</button>}</div>}</div></>}
    </section>
    <section className="about-section" id="about"><div className="shell about-grid"><div className="about-heading"><span className="section-icon"><Building size={24} /></span><p className="eyebrow">About this portal</p><h2>Community records, made easier to access.</h2></div><p>This document center provides residents, owners, and the public with convenient access to official association records and current community information. Documents are organized for quick reference and maintained by property management.</p></div></section>
    <section className="contact-section shell" id="contact"><div><p className="eyebrow">Questions or assistance</p><h2>Contact property management</h2><p>For questions about a document or to request additional association records, contact the management office.</p></div><address className="contact-details"><strong>{siteConfig.contact.label}</strong><a href={`mailto:${siteConfig.contact.email}`}><Mail size={18}/>{siteConfig.contact.email}</a><a href={`tel:${siteConfig.contact.phoneHref}`}><Phone size={18}/>{siteConfig.contact.phone}</a></address></section>
  </main>;
}
